apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sobel-workers
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
      - sobel
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: [worker, centralizador]
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
