services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"       
      - "15672:15672"     
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10

  producer:
    build: ./producer
    depends_on:
      rabbitmq:
        condition: service_healthy  
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONUNBUFFERED=1 
           
  consumer:
    build: ./consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONUNBUFFERED=1 

  consumerdlq:
    build: ./consumerDLQ
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONUNBUFFERED=1 
          


