# Usar una imagen base de Python
FROM python:3.11-slim

# Setear directorio de trabajo
WORKDIR /app

# Copiar archivos
COPY producer.py .

# Instalar dependencias
RUN pip install --no-cache-dir pika

# Comando por defecto
CMD ["python", "producer.py"]