apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: sobel
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
